// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTN01ZjfRMi67_DArIqo3DJ8iBbQoi9Kc',
    appId: '1:1079144779143:web:e492d9283f256532975722',
    messagingSenderId: '1079144779143',
    projectId: 'fav-flutter-fb',
    authDomain: 'fav-flutter-fb.firebaseapp.com',
    storageBucket: 'fav-flutter-fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHbdQVWaZ1twThxDDJn5vloC1kIvbleck',
    appId: '1:1079144779143:android:26c4672fb5bde90e975722',
    messagingSenderId: '1079144779143',
    projectId: 'fav-flutter-fb',
    storageBucket: 'fav-flutter-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePHVlSCtxX6WOhVBU7P03_0cYnOF6DJg',
    appId: '1:1079144779143:ios:a9341cc27c252469975722',
    messagingSenderId: '1079144779143',
    projectId: 'fav-flutter-fb',
    storageBucket: 'fav-flutter-fb.appspot.com',
    iosBundleId: 'com.example.favFlutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePHVlSCtxX6WOhVBU7P03_0cYnOF6DJg',
    appId: '1:1079144779143:ios:a9341cc27c252469975722',
    messagingSenderId: '1079144779143',
    projectId: 'fav-flutter-fb',
    storageBucket: 'fav-flutter-fb.appspot.com',
    iosBundleId: 'com.example.favFlutterFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTN01ZjfRMi67_DArIqo3DJ8iBbQoi9Kc',
    appId: '1:1079144779143:web:390cc2bb7080c6e1975722',
    messagingSenderId: '1079144779143',
    projectId: 'fav-flutter-fb',
    authDomain: 'fav-flutter-fb.firebaseapp.com',
    storageBucket: 'fav-flutter-fb.appspot.com',
  );
}
